-- MySQL Script generated by MySQL Workbench
-- mar 03 oct 2017 21:11:59 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prestamosuesocc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prestamosuesocc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prestamosuesocc` DEFAULT CHARACTER SET latin1 ;
USE `prestamosuesocc` ;

-- -----------------------------------------------------
-- Table `prestamosuesocc`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`balance` (
  `id_cuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cuenta` VARCHAR(45) NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_cuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `clave` CHAR(32) NOT NULL,
  `rol` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`bitacora` (
  `id_bitacora` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `accion` TEXT NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `prestamosuesocc`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`cliente` (
  `dui` CHAR(10) NOT NULL,
  `nit` CHAR(17) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) CHARACTER SET 'big5' NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefonos` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dui`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`prestamo` (
  `id_prestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `dui` CHAR(10) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `valor_cuota` DOUBLE NOT NULL,
  `tasa_interes` DOUBLE NOT NULL,
  `cantidad_cuotas` INT(3) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_ultimo_pago` DATE NULL DEFAULT NULL,
  `saldo` DOUBLE NOT NULL,
  `estado` CHAR(1) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `capitalizacion` CHAR(1) NOT NULL,
  `tasa_mora` DOUBLE NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_prestamo_cliente1_idx` (`dui` ASC),
  CONSTRAINT `fk_prestamo_cliente1`
    FOREIGN KEY (`dui`)
    REFERENCES `prestamosuesocc`.`cliente` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`cuota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`cuota` (
  `id_prestamo` INT(11) NOT NULL,
  `num_cuota` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `interes` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `capital` DOUBLE NOT NULL,
  `saldo_anterior` DOUBLE NOT NULL,
  `saldo_actualizado` DOUBLE NOT NULL,
  `mora` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_prestamo`, `num_cuota`),
  CONSTRAINT `fk_cuota_prestamo`
    FOREIGN KEY (`id_prestamo`)
    REFERENCES `prestamosuesocc`.`prestamo` (`id_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`documento` (
  `dui` CHAR(10) NOT NULL,
  `correlativo` INT(11) NOT NULL,
  `nombre_archivo` TEXT NOT NULL,
  `archivo` BLOB NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`dui`, `correlativo`),
  CONSTRAINT `fk_documentos_cliente1`
    FOREIGN KEY (`dui`)
    REFERENCES `prestamosuesocc`.`cliente` (`dui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`estado_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`estado_resultados` (
  `id_cuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cuenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`movimientos_er`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`movimientos_er` (
  `id_cuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  CONSTRAINT `id_cuenta`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `prestamosuesocc`.`estado_resultados` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prestamosuesocc`.`parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prestamosuesocc`.`parametro` (
  `id_parametro` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `valor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_parametro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
